<a href="https://colab.research.google.com/github/leminhviett/Chatbot/blob/master/buildingModeChatBot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
data_path = '/content/drive/My Drive/data/ChatBot/'

import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

import numpy as np
import random
import json

In [0]:
import warnings
warnings.filterwarnings("ignore")

In [0]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

# 1. Pre-processing Data

In [0]:
words = []
labels = []
docs_x = []
docs_y = []
with open(data_path + 'train.json') as file:
    data = json.load(file)
    for intent in data['intents']:
      for pattern in intent['patterns']:
        wrds = nltk.word_tokenize(pattern)
        words.extend(wrds)
        docs_x.append(wrds)
        docs_y.append(intent['tag'])
      if intent['tag'] not in labels:
        labels.append(intent['tag'])

In [0]:
print('labels: ', labels)
print('words: ', words)
print('docs_x: ', docs_x)
print('docs_y: ', docs_y)

labels:  ['greeting', 'goodbye', 'thanks', 'hours', 'name', 'food', 'interests', 'number', 'family', 'location']
words:  ['Hi', 'How', 'are', 'you', 'Is', 'anyone', 'there', '?', 'Hello', 'Good', 'day', 'Bye', 'See', 'you', 'later', 'Goodbye', 'Thanks', 'Thank', 'you', 'That', "'s", 'helpful', 'What', 'hours', 'are', 'you', 'open', '?', 'what', 'is', 'your', 'working', 'hours', '?', 'When', 'will', 'you', 'close', '?', 'What', 'is', 'your', 'name', '?', 'How', 'can', 'I', 'call', 'you', '?', 'Do', 'you', 'have', 'a', 'name', '?', 'Who', 'are', 'you', 'What', 'do', 'you', 'eat', '?', 'Do', 'you', 'eat', 'food', '?', 'Why', 'you', 'do', "n't", 'eat', 'What', 'are', 'your', 'interests', 'What', 'are', 'your', 'favorite', 'subjects', 'What', 'are', 'your', 'interests', 'What', 'is', 'your', 'number', 'What', 'is', 'your', 'number', 'What', 'is', 'your', 'favorite', 'number', 'What', 'is', 'your', 'father', 'Do', 'you', 'have', 'any', 'siblings', 'Who', 'is', 'your', 'brothers', 'Where', 'a

In [0]:
# stem & sort the words list
words = [stemmer.stem(w.lower()) for w in words if w != "?"]
words = sorted(list(set(words)))
# sort the labels
labels = sorted(labels)
print('labels: ', labels)
print('words: ', words)

labels:  ['family', 'food', 'goodbye', 'greeting', 'hours', 'interests', 'location', 'name', 'number', 'thanks']
words:  ["'s", 'a', 'any', 'anyon', 'ar', 'broth', 'bye', 'cal', 'can', 'clos', 'day', 'do', 'eat', 'fath', 'favorit', 'food', 'from', 'good', 'goodby', 'hav', 'hello', 'help', 'hi', 'hour', 'how', 'i', 'interest', 'is', 'lat', 'loc', "n't", 'nam', 'numb', 'op', 'see', 'sibl', 'subject', 'thank', 'that', 'ther', 'what', 'when', 'wher', 'who', 'why', 'wil', 'work', 'yo', 'you']


In [0]:
features = []
target = []

for i, doc in enumerate(docs_x):
  sub_features = []
  wrds = [stemmer.stem(w) for w in doc]
  for w in words:
    if w in wrds:
      sub_features.append(1)
    else:
      sub_features.append(0)
  features.append(sub_features)
  
  col = labels.index(docs_y[i])
  target.append(col)

print('features: ', features)
print('target: ', target)


features:  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 

In [0]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [0]:
features = torch.from_numpy(np.array(features)).type(torch.FloatTensor)
target = torch.from_numpy(np.array(target))
print(features.size(), target.shape)
print(features)

torch.Size([33, 49]) torch.Size([33])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])


# 2. Define Model

In [0]:
class DNNModel(nn.Module):
  def __init__(self, inp_dim, out_dim):
    super().__init__()
    self.fc1 = nn.Linear(inp_dim, 10)
    self.fc2 = nn.Linear(10, 10)
    self.fc3 = nn.Linear(10, out_features=out_dim)
  def forward(self, inp):
    out = self.fc1(inp)
    out = F.relu(out)
    out = self.fc2(out)
    out = F.tanh(out)
    out = self.fc2(out)
    out = F.elu(out)
    return out

In [0]:
model = DNNModel(features.size()[1], 6)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)
loss_fn = nn.CrossEntropyLoss()

In [0]:
model.train()
for i in range(4000):
  predicted = model(features)

  optimizer.zero_grad()
  loss = loss_fn(predicted, target)
  loss.backward()
  optimizer.step()

  if(i%200 == 0):
    prediction = torch.max(predicted, 1)[1]
    correct = (prediction == target).sum()
    accuracy = correct/float(target.size()[0])
    print("iter = {}, loss = {}, accuracy = {}".format(i, loss, accuracy))

iter = 0, loss = 2.315319299697876, accuracy = 0.09090909361839294
iter = 200, loss = 2.29306697845459, accuracy = 0.1515151560306549
iter = 400, loss = 2.2760398387908936, accuracy = 0.1515151560306549
iter = 600, loss = 2.253408908843994, accuracy = 0.1515151560306549
iter = 800, loss = 2.221125841140747, accuracy = 0.1818181872367859
iter = 1000, loss = 2.1713104248046875, accuracy = 0.3030303120613098
iter = 1200, loss = 2.1027915477752686, accuracy = 0.3030303120613098
iter = 1400, loss = 2.0156517028808594, accuracy = 0.3636363744735718
iter = 1600, loss = 1.905890703201294, accuracy = 0.3636363744735718
iter = 1800, loss = 1.7683182954788208, accuracy = 0.3636363744735718
iter = 2000, loss = 1.6070927381515503, accuracy = 0.42424243688583374
iter = 2200, loss = 1.430072546005249, accuracy = 0.4545454680919647
iter = 2400, loss = 1.2333738803863525, accuracy = 0.6666666865348816
iter = 2600, loss = 1.0252197980880737, accuracy = 0.9090909361839294
iter = 2800, loss = 0.8285780549

In [0]:
test = bag_of_words('thank you', words)
print(test)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])


In [0]:
print(F.softmax(model(test)))

tensor([0.0045, 0.3205, 0.0067, 0.0116, 0.0043, 0.0592, 0.0027, 0.0226, 0.0026,
        0.5653], grad_fn=<SoftmaxBackward>)


In [0]:
def chat():
  print('Enter chat. Press q to quit')
  while True:
    print('You: ', end="")
    x = input()
    if(x == 'q'):
      break

    output = model(bag_of_words(x, words))
    out_max_point = torch.max(F.softmax(output), 0)[0].data
    print('Bot: ', end="")
    if( out_max_point < 0.5):
      print("Sorry .I don't understand. Ask another question !")
    else:
      response_index = torch.max(output, 0)[1].data
      response = labels[response_index]
      for i, res in enumerate(data["intents"]):
          if res['tag'] == response:
            responses = res['responses']
      print(random.choice(responses))

In [0]:
chat()

Enter chat. Press q to quit
You: hi
Bot: Hi there, how can I help?
You: what is your name ?
Bot: SimpleBot !
You: what is your working hour ?
Bot: I am always here to serve you
You: oh, thank you a lot !
Bot: Sorry .I don't understand. Ask another question !
You: thank you 
Bot: Any time!
You: what do you eat ?
Bot: I consume RAM, and binary digits.
You: where is your location ?
Bot: Internet is my home
You: thanks
Bot: Happy to help!
You: bye
Bot: See you later, thanks for visiting
You: q
